# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a7359ecf8d8d5f14d81fa3c9e85cbe81"
application_url = "https://simple-payment-customizer.onrender.com"
embedded = true
name = "simple-payment-customizer"
handle = "simple-payment-customizer-2"

[build]
include_config_on_deploy = true
dev_store_url = "simple-payment-customizer.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_payment_terms,write_payment_customizations"

[auth]
redirect_urls = [
  "https://simple-payment-customizer.onrender.com/auth/callback",
  "https://simple-payment-customizer.onrender.com/auth/shopify/callback",
  "https://simple-payment-customizer.onrender.com/api/auth/callback"
]

[pos]
embedded = false
